### ISSUE TITLE
Let's remove react for now

### ISSUE THREAD

**Issue by lambtron** [deyyanl/oak-deno-crud#4]
I do love the idea of the educational content extending to building a react frontend. let's do this for Part II of the series? for now we can just do a CRUD API and all of the screenshots will simply be JSON in the browser (see example: https://deno.com/blog/build-crud-api-oak-denokv)

**Comment by deyyanl** [comment]
Hey @lambtron, thanks for the review! Appreciate it. I will close these issues, as they are now completed. 

Let me know if you have any further comments by opening new issues. 

Best,
D
